In [1]:
import numpy as np
import pandas as pd

### 1、处理缺失数据

In [2]:
string_data = pd.Series(['aardvark', 'artichoke', np.nan, 'avocado'])
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [3]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [4]:
string_data[0] = None
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

In [6]:
from numpy import nan as NA

data = pd.Series([1, NA, 3.5, NA, 7])
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [7]:
data = pd.DataFrame([[1., 6.5, 3.], [1., NA, NA],
   ....:                      [NA, NA, NA], [NA, 6.5, 3.]])
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [9]:
cleaned = data.dropna()
cleaned

0    1    2
0  1.0  6.5  3.0

In [10]:
data.dropna(how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [11]:
df = pd.DataFrame(np.random.randn(7, 3))
df.iloc[:4, 1] = NA
df.iloc[:2, 2] = NA
df

0         1         2
0  0.412559       NaN       NaN
1 -0.033614       NaN       NaN
2 -0.022649       NaN  0.190577
3 -1.668947       NaN  1.106416
4 -0.719374  1.814645  1.203591
5  2.837162  0.352159 -0.498540
6  1.032590 -1.084548 -0.545368

In [12]:
df.fillna(0)

0         1         2
0  0.412559  0.000000  0.000000
1 -0.033614  0.000000  0.000000
2 -0.022649  0.000000  0.190577
3 -1.668947  0.000000  1.106416
4 -0.719374  1.814645  1.203591
5  2.837162  0.352159 -0.498540
6  1.032590 -1.084548 -0.545368

In [13]:
df.fillna({1:0.5,2:0})

0         1         2
0  0.412559  0.500000  0.000000
1 -0.033614  0.500000  0.000000
2 -0.022649  0.500000  0.190577
3 -1.668947  0.500000  1.106416
4 -0.719374  1.814645  1.203591
5  2.837162  0.352159 -0.498540
6  1.032590 -1.084548 -0.545368

In [14]:
data = pd.Series([1., NA, 3.5, NA, 7])
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

### 2、数据转换

In [15]:
data = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'],
   ....:                      'k2': [1, 1, 2, 3, 3, 4, 4]})
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [16]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [17]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [18]:
data['v1'] = range(7)
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
1  two   1   1

In [19]:
data.drop_duplicates(['k1','k2'],keep='last')

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [20]:
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon',
   ....:                               'Pastrami', 'corned beef', 'Bacon',
   ....:                               'pastrami', 'honey ham', 'nova lox'],
   ....:                      'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [21]:
meat_to_animal = {
  'bacon': 'pig',
  'pulled pork': 'pig',
  'pastrami': 'cow',
  'corned beef': 'cow',
  'honey ham': 'pig',
  'nova lox': 'salmon'
}

lowercase = data['food'].str.lower()
lowercase

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [22]:
data['animal'] = lowercase.map(meat_to_animal)
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [23]:
data['food'].map(lambda x: meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [24]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [25]:
data.replace(-999,np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [26]:
data.replace([-999,-1000],np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [27]:
data.replace([-999,-1000],[np.nan,0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [28]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
   ....:                     index=['Ohio', 'Colorado', 'New York'],
   ....:                     columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [29]:
data.rename(index=str.title,columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [30]:
data.rename(index={'OHIO':'INDIANA'},columns={'three':'peekaboo'})

one  two  peekaboo  four
Ohio        0    1         2     3
Colorado    4    5         6     7
New York    8    9        10    11

In [33]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

bins = [18,25,35,60,100]
cats = pd.cut(ages,bins)
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [34]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [35]:
pd.value_counts(cats)

(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
dtype: int64

In [37]:
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']
pd.cut(ages,bins,labels=group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [38]:
data = np.random.rand(20)
pd.cut(data,4,precision=2)

[(0.02, 0.26], (0.02, 0.26], (0.02, 0.26], (0.74, 0.99], (0.26, 0.5], ..., (0.5, 0.74], (0.5, 0.74], (0.02, 0.26], (0.74, 0.99], (0.5, 0.74]]
Length: 20
Categories (4, interval[float64, right]): [(0.02, 0.26] < (0.26, 0.5] < (0.5, 0.74] < (0.74, 0.99]]

In [39]:
data = pd.DataFrame(np.random.randn(1000, 4))
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.014002     0.013347     0.010571    -0.000720
std       0.997938     0.989616     0.964776     1.014622
min      -3.174171    -3.029996    -2.599818    -3.544357
25%      -0.681290    -0.650870    -0.652402    -0.693073
50%      -0.016101     0.020266     0.003679     0.035440
75%       0.661122     0.663595     0.647667     0.694696
max       3.676301     3.047825     3.147184     3.786119

In [41]:
data[np.abs(data) > 3] = np.sign(data) * 3
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.015168     0.013329     0.010387    -0.000439
std       0.992882     0.989379     0.964195     1.008624
min      -3.000000    -3.000000    -2.599818    -3.000000
25%      -0.681290    -0.650870    -0.652402    -0.693073
50%      -0.016101     0.020266     0.003679     0.035440
75%       0.661122     0.663595     0.647667     0.694696
max       3.000000     3.000000     3.000000     3.000000

In [42]:
np.sign(data).head()

0    1    2    3
0  1.0  1.0 -1.0  1.0
1 -1.0 -1.0  1.0 -1.0
2  1.0 -1.0  1.0 -1.0
3 -1.0  1.0 -1.0 -1.0
4 -1.0 -1.0 -1.0 -1.0

In [44]:
sampler = np.random.permutation(5)
sampler

array([1, 3, 2, 0, 4])

In [45]:
df = pd.DataFrame(np.arange(5 * 4).reshape((5, 4)))
df.take(sampler)

0   1   2   3
1   4   5   6   7
3  12  13  14  15
2   8   9  10  11
0   0   1   2   3
4  16  17  18  19

In [46]:
df.sample(3)

0   1   2   3
2   8   9  10  11
0   0   1   2   3
3  12  13  14  15

In [48]:
df = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],
   .....:                    'data1': range(6)})
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [49]:
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [51]:
dummies = pd.get_dummies(df['key'],prefix='key')
df_with_dummies = df[['data1']].join(dummies)
df_with_dummies

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [52]:
values = np.random.rand(10)
values

array([0.72012679, 0.34377716, 0.26912688, 0.87127734, 0.35991223,
       0.2446955 , 0.39983216, 0.60763054, 0.72269369, 0.97486335])

In [53]:
bins = [0,0.2,0.4,0.6,0.8,1]
pd.get_dummies(pd.cut(values,bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           1           0
1           0           1           0           0           0
2           0           1           0           0           0
3           0           0           0           0           1
4           0           1           0           0           0
5           0           1           0           0           0
6           0           1           0           0           0
7           0           0           0           1           0
8           0           0           0           1           0
9           0           0           0           0           1

### 3、字符串操作

In [55]:
val = 'a,b,  guido'
val.split(',')

['a', 'b', '  guido']

In [56]:
pieces = [x.strip() for x in val.split(',')]
pieces

['a', 'b', 'guido']

In [57]:
first, second, third = pieces
first + '::' + second + '::' + third

'a::b::guido'

In [58]:
'::'.join(pieces)

'a::b::guido'

In [59]:
'guido' in val

True

In [60]:
val.count(',')

2

In [61]:
val.replace(',','')

'ab  guido'

In [62]:
import re

text = "foo    bar\t baz  \tqux"
re.split('\s+',text)

['foo', 'bar', 'baz', 'qux']

In [63]:
regex = re.compile('\s+')
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [64]:
regex.findall(text)

['    ', '\t ', '  \t']

In [65]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com
"""
pattern = r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}'
regex = re.compile(pattern,flags=re.IGNORECASE)

regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [66]:
regex.search(text)

<re.Match object; span=(5, 20), match='dave@google.com'>

In [68]:
print(regex.match(text))

None


In [69]:
print(regex.sub('REDACTED',text))

Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED



In [70]:
pattern = r'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})'
regex = re.compile(pattern,flags=re.IGNORECASE)

m = regex.match('caiyu@163.com')
m.groups()

('caiyu', '163', 'com')

In [71]:
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [72]:
print(regex.sub(r'Username:\1,Domain:\2,Suffix:\3',text))

Dave Username:dave,Domain:google,Suffix:com
Steve Username:steve,Domain:gmail,Suffix:com
Rob Username:rob,Domain:gmail,Suffix:com
Ryan Username:ryan,Domain:yahoo,Suffix:com



In [74]:
data = {'Dave': 'dave@google.com', 'Steve': 'steve@gmail.com',
   .....:         'Rob': 'rob@gmail.com', 'Wes': np.nan}
data = pd.Series(data)
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [75]:
data.str.contains('gmail')

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [76]:
data.str.findall(pattern,flags=re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [78]:
matches = data.str.match(pattern,flags=re.IGNORECASE)
matches

Dave     True
Steve    True
Rob      True
Wes       NaN
dtype: object

In [79]:
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: object